### ISSUE TITLE
Description Of column Names

### ISSUE THREAD

**Issue by BhaveshMotwani** [California-Data-Collaborative/Sewer_Overflow_Data_Challenge#2]
The links provided in the description do explain the meaning of the datasets whereas it would be quite helpful if we could get a brief description of the column names inside of each dataset.
Some of the columns are self explanatory while some aren't.
It would be very helpful if we could get some description of the column names inside of the data sets.

**Comment by patwater** [comment]
See here again for the column name dictionary: http://www.waterboards.ca.gov/water_issues/programs/sso/glossary.shtml

Perhaps you could please add more specific questions on specific columns if you have them?
