### ISSUE TITLE
Feature to subset the data

### ISSUE THREAD

**Issue by BhaveshMotwani** [California-Data-Collaborative/Sewer_Overflow_Data_Challenge#3]
Hello Sir,

Can you please tell me the feature that should be selected to subset the data for analysis.

Do you want the graphs to display analysis of each WDID as that would contain more than 1092 subsets to do our analysis on
or do you want the analysis to be done for each county,in that case there would be 58 subsets.

**Comment by patwater** [comment]
Hi I think it would be most usefuly to do by WDID / SSO and then just prune the graphs to the area of interest.  Say breaking out the top 20 SSO's by total spill volume over time etc
